name: bahn_bingo
description: Bingo with your friends while riding the train

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'
  
dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # A
  another_flushbar: ^1.12.29
  # B
  # C
  cupertino_icons: ^1.0.5
  # D
  dio: ^5.1.1
  # E
  event_bus: ^2.0.0
  # F
  flutter_mobx: ^2.0.6+5
  # G
  get_it: ^7.2.0
  google_fonts: ^4.0.3
  # H
  http: ^0.13.5
  # I
  intl: ^0.18.0
  # J
  json_serializable: ^6.7.1
  # K
  # L
  # M
  material_dialog: ^1.0.0-nullsafety.1
  mobx: ^2.1.4
  # N
  # O
  # P
  path_provider: ^2.0.14
  # Q
  # R
  # S
  shared_preferences: ^2.1.0
  sembast_web: ^2.1.3
  sembast: ^3.4.4
  # T
  # U
  # V
  validators: ^3.0.0
  # W
  # X
  xxtea: ^2.1.0
  ionicons: ^0.2.2
  flutter_screenutil: ^5.9.0
  material_color_utilities: ^0.5.0
  firebase_core: ^2.20.0
  cloud_firestore: ^4.12.0
  firebase_auth: ^4.12.0
  uuid: ^4.1.0
  jose: ^0.3.4
  json_annotation: ^4.8.1
  flutter_animate: ^4.2.0+1
  share_plus: ^7.2.1
  # Y
  # Z

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1
  mobx_codegen: ^2.2.0
  build_runner: ^2.3.3
  analyzer: ^5.10.0

flutter_launcher_icons:
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icons/android/play_store_512.png"
  image_path: "assets/icons/ios/AppIcon-ipad.png"
  android: true
  ios: true
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/icons/web/icon-512.png"
    background_color: "#ffffff"
    theme_color: "#fa1c28"

flutter:

  uses-material-design: true

  assets:
  - assets/images/
  - assets/icons/
  - assets/lang/
