// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFrcuQhC31Bnif2FRh088QJcUAlMmB2DM',
    appId: '1:1049599616465:web:363733ccc4d94043bfacf0',
    messagingSenderId: '1049599616465',
    projectId: 'bahnbingo-3104c',
    authDomain: 'bahnbingo-3104c.firebaseapp.com',
    storageBucket: 'bahnbingo-3104c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPpykbv2vGAMZYPiRkfkeqAevGtEoi2EQ',
    appId: '1:1049599616465:android:9df31f37c5848087bfacf0',
    messagingSenderId: '1049599616465',
    projectId: 'bahnbingo-3104c',
    storageBucket: 'bahnbingo-3104c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEfX5AuAf_9U2zfUrDqf5W6vff4xOPH9c',
    appId: '1:1049599616465:ios:593aeaa0b2549626bfacf0',
    messagingSenderId: '1049599616465',
    projectId: 'bahnbingo-3104c',
    storageBucket: 'bahnbingo-3104c.appspot.com',
    iosBundleId: 'com.iotecksolutions.flutterBoilerplateProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEfX5AuAf_9U2zfUrDqf5W6vff4xOPH9c',
    appId: '1:1049599616465:ios:4a35b4242c9eacf7bfacf0',
    messagingSenderId: '1049599616465',
    projectId: 'bahnbingo-3104c',
    storageBucket: 'bahnbingo-3104c.appspot.com',
    iosBundleId: 'com.iotecksolutions.flutterBoilerplateProject.RunnerTests',
  );
}
